server:
  port: 8080

spring:

  application:
    name: spring-security-client

  datasource:
    url: jdbc:mysql://localhost:3306/mydb_01
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
